# Generated by Django 5.2 on 2025-10-08 07:51

import apps.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeVaultFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to=apps.models.vault_file_path)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_files",
                        to="apps.employeeprofile",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can access this file",
                        related_name="shared_vault_files",
                        to="apps.employeeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vault File",
                "verbose_name_plural": "Vault Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
