# Generated by Django 5.2 on 2025-10-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_conversation_chatmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatMessage",
            new_name="Message",
        ),
    ]
