# Generated by Django 5.2 on 2025-10-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_rename_chatmessage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
